### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by teayettle** [Mister4Eyes/Source-Randomizer#1]
^^^

**Comment by Mister4Eyes** [comment]
Did you find out how this works?
In case you didn't, you either type in the directory to the game or drag and drop the folder on the executable. Once you do that, just select the options it gives you.

**Comment by teayettle** [comment]
No, but I can't get past the 'Getting valid vpks' in the latest release. (Legacy Version SR works fine)

**Comment by teayettle** [comment]
Well now it says "Can't find assets" and plays the normal HL2. (newest version)

**Comment by Mister4Eyes** [comment]
I'ts been about a year since I messed with it so I'd recommend using the legacy one right now. I might remake this into something later but in it's current state I can't tell whats wrong. Sorry I can't help more.
